### ISSUE TITLE
How not to strip empty lines?

### ISSUE THREAD

**Issue by d9k** [gulp-community/gulp-coffee#92]
input:

```
console.log 1



console.log 2


```

coffeescript compiler output:

```
(function() {
  console.log(1);

  console.log(2);

}).call(this);
```

expected output:

```
(function() {
  console.log(1);



  console.log(2);


}).call(this);
```

How not to strip empty lines?

**Comment by contra** [comment]
This would be a ticket for coffee-script itself - they might have an option for maintaining whitespace already.

**Comment by d9k** [comment]
No, they don't https://github.com/jashkenas/coffeescript/issues/5064
