### ISSUE TITLE
Needs new release to remove merge vulnerability

### ISSUE THREAD

**Issue by nathancarter** [gulp-community/gulp-coffee#94]
I notice that your latest commits removed the unneeded "merge" library.  Many of us who use `gulp-coffee` just got a security alert email (or a jillion of them) saying that we depend upon an insecure merge library through `gulp-coffee`.  We can't fix the problem until those commits go into npm.  Can you do a point release please, or whatever you think is appropriate?  Thank you!

**Comment by yocontra** [comment]
3.0.3 is published

**Comment by nathancarter** [comment]
Thank you!  I'm working through bugs in other tools, trying to get this integrated correctly, but I appreciate the quick reply!
